### ISSUE TITLE
Can the output form be improved? For example, (ip:port) open

### ISSUE THREAD

**Issue by AuFeng111** [elddy/NimScan#5]
I like this port scanner very much, it is fast and accurate, but the output format is not very friendly

**Comment by elddy** [comment]
Thank you! I'll work on it

**Comment by elddy** [comment]
Updated the output format, hope you find it friendly

**Comment by AuFeng111** [comment]
It would be nice if the author could compile Nimscan for Windows ，thanks in advance
--------------------------------------
For help
The recvFrom function takes a buf argument of type CString, but it is actually given an Array [0..65535, CHAR].
NIM Compiler Version 1.4.4 [Windows: AMD64]
TerminalTables module and WinIM module are installed
![image](https://user-images.githubusercontent.com/58653994/110412745-a5984880-80c7-11eb-80d1-774af6bfc7fa.png)

**Comment by elddy** [comment]
There is an issue with the NIM Compiler version 1.4.4 and if I'll change the Array [0..65535, CHAR] to CString, the recvfrom function will not work properly.
![image](https://user-images.githubusercontent.com/69467775/110456844-b39f9680-80d2-11eb-9482-e2e6b5f8d59e.png)

I suggest using an older Nim version (I use 1.2.4) and it will compile fine.
